name: Backup to S3

on:
  push:
    branches:
      - main
  schedule:
    - cron: '11 17 * * *'
jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Zip repo
      run: zip -r repo.zip .
      
    - name: Copy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: >
          --acl private 
          --follow-symlinks 
          --delete 
          --region us-east-2
          --access-key ${{ secrets.AWS_ACCESS_KEY_ID }}
          --secret-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          --bucket ${{ secrets.AWS_S3_BUCKET }}
          --source "repo.zip"

