name: Backup to S3

on:
  push:
    branches:
      - main
  schedule:
    - cron: '11 17 * * *'
jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Zip repo
      run: zip -r repo.zip .

    - name: Upload repo.zip to S3 bucket
      uses: tpaschalis/s3-sync-action@master
      with:
        args: --acl private
      env:
        FILE: ./repo.zip
        AWS_REGION: 'us-east-2'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
          

